name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  format:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - run: npm ci
      - run: npm exec nx -- format:check

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install chrome-beta msedge-dev --with-deps

      - run: npm exec nx -- run-many -t lint typecheck test build e2e
